# Generated by Django 4.0.4 on 2022-05-29 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('employees_count', models.IntegerField(verbose_name='Число сотрудников')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Работодатель',
                'verbose_name_plural': 'Работодатели',
            },
        ),
        migrations.CreateModel(
            name='Finder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('cv', models.FileField(upload_to='cv', verbose_name='Файл резюме')),
                ('photo', models.ImageField(upload_to='img/user_photos', verbose_name='Фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employer', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланировано'), ('PROCESSING', 'В процессе'), ('FINISHED', 'Окончено')], max_length=255, verbose_name='')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employer', verbose_name='Работодатель')),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.finder', verbose_name='Соискатель')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Собеседование',
                'verbose_name_plural': 'Собеседования',
            },
        ),
    ]
