# Generated by Django 4.0.4 on 2022-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_finder_cv_alter_finder_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv', verbose_name='Файл резюме'),
        ),
        migrations.AlterField(
            model_name='finder',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/user_photos', verbose_name='Фото'),
        ),
    ]
