# Generated by Django 4.0.4 on 2022-07-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historicalvacancy_historicalinterview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvacancy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание вакансии'),
        ),
    ]
